name: login_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  webview_flutter: ^4.0.0
  webview_windows: ^0.4.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon/
    - assets/images/floor/
    - assets/images/background/
    - assets/images/character/
