name: login_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^4.0.0
  webview_windows: ^0.4.0
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.3
  provider: ^6.1.2
  device_info_plus: ^11.1.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  visibility_detector: ^0.4.0+2
  intl: ^0.20.0
  win32: ^5.8.0
  ffi: ^2.1.3
  launch_at_startup: ^0.3.1
  tray_manager: ^0.3.0
  window_manager: ^0.4.3
  windows_single_instance: ^1.0.1
  package_info_plus: ^8.1.1
  unique_identifier: ^0.4.0
  windows_notification: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/character/
    - assets/items/background/
    - assets/items/floor/
    - assets/images/icon/
    - assets/images/profile/
    - assets/images/start/
    - assets/images/trash/
    - assets/items/items.json
    - lib/data/user/user_data.json
    - assets/design1.png
    - assets/digital_CO2.png
    - assets/images/tray/tray_icon.ico
    - assets/images/tray/tray_icon.png
    - lib/screen/home/missions.json
